// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Participant = __t.object("Participant", {
  id: __t.string(),
  roomId: __t.string(),
  participantId: __t.string(),
  name: __t.string(),
  ready: __t.bool(),
  hasSelection: __t.bool(),
  connected: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type Participant = __Infer<typeof Participant>;

export const ParticipantConnection = __t.object("ParticipantConnection", {
  connectionId: __t.connectionId(),
  id: __t.string(),
  roomId: __t.string(),
  participantId: __t.string(),
});
export type ParticipantConnection = __Infer<typeof ParticipantConnection>;

export const RevealedVote = __t.object("RevealedVote", {
  id: __t.string(),
  roomId: __t.string(),
  participantId: __t.string(),
  selectedValue: __t.string(),
  phaseVersion: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type RevealedVote = __Infer<typeof RevealedVote>;

export const Room = __t.object("Room", {
  roomId: __t.string(),
  phase: __t.string(),
  phaseVersion: __t.u64(),
  resetVersion: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

export const Vote = __t.object("Vote", {
  id: __t.string(),
  roomId: __t.string(),
  participantId: __t.string(),
  selectedValue: __t.string(),
  updatedAt: __t.timestamp(),
});
export type Vote = __Infer<typeof Vote>;
