// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import HideRoomReducer from "../hide_room_reducer";
import JoinRoomReducer from "../join_room_reducer";
import ResetRoomReducer from "../reset_room_reducer";
import RevealRoomReducer from "../reveal_room_reducer";
import SelectCardReducer from "../select_card_reducer";
import SetNameReducer from "../set_name_reducer";
import SetReadyReducer from "../set_ready_reducer";

export type HideRoomParams = __Infer<typeof HideRoomReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type ResetRoomParams = __Infer<typeof ResetRoomReducer>;
export type RevealRoomParams = __Infer<typeof RevealRoomReducer>;
export type SelectCardParams = __Infer<typeof SelectCardReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SetReadyParams = __Infer<typeof SetReadyReducer>;
